#!/bin/sh

sudo apt install jq iputils-ping bind9-dnsutils bind9-host fping iw minicom vim nmap ntfs-3g exfatprogs oathtool p7zip-full rsync rclone snmp sqlite3 mariadb-client tree ncdu gtkterm tcpdump wireshark ldap-utils git freerdp3-x11 curl wget tmux smbclient netcat-openbsd telnet openssh-client sshfs iperf3 crudini genisoimage libxml2-utils yamllint dmg2img

# libxml2-utils = xmllint

sudo usermod -aG wireshark $(whoami)
