#!/bin/sh

sudo apt install xinit i3-wm arandr dunst dmenu alacritty xss-lock numlockx slock xcompmgr network-manager-gnome dex scrot rofi redshift

../common/setup-pipewire
../common/setup-mate-utils
../common/setup-lf
