#!/bin/sh

sudo apt install xinit i3-wm i3blocks arandr dunst dmenu alacritty xss-lock numlockx slock xcompmgr network-manager-gnome dex scrot rofi redshift lf

../common/setup-pipewire
../common/setup-mate-utils
