#!/bin/sh

../common/setup-flatpak
../common/setup-yt-dlp

../apply audio

sudo apt install gimp ffmpeg mpv imagemagick obs-studio obs-cli simplescreenrecorder obs-pipewire-audio-capture obs-retro-effects obs-vintage-filter
flatpak install flathub org.kde.kdenlive
