#!/bin/sh

dpkg -l | grep temurin && exit 0

if [ -z "$JAVA_VERSION" ]; then
    JAVA_VERSION=25
fi

sudo apt install -y wget apt-transport-https gpg
wget -qO - https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/adoptium.gpg > /dev/null
echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | sudo tee /etc/apt/sources.list.d/adoptium.list
sudo apt update
sudo apt install "temurin-${JAVA_VERSION}-jre" "temurin-${JAVA_VERSION}-jdk"
