#!/bin/sh

# some debian isos come with firefox-esr pre-installed
if command -v firefox-esr > /dev/null; then
    sudo cp policies.json /usr/lib/firefox-esr/distribution/policies.json
    exit 0
fi

if command -v firefox > /dev/null; then
    exit 0
fi

sudo apt install -y wget
sudo install -d -m 0755 /etc/apt/keyrings
wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | sudo tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null
echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | sudo tee -a /etc/apt/sources.list.d/mozilla.list > /dev/null
echo '
Package: *
Pin: origin packages.mozilla.org
Pin-Priority: 1000
' | sudo tee /etc/apt/preferences.d/mozilla 
sudo apt update && sudo apt install firefox

sudo cp policies.json /usr/lib/firefox/distribution/policies.json

../common/setup-pipewire
