#!/bin/bash

qemu-system-x86_64 \
	-enable-kvm \
	-m 5G \
	-device ich9-ahci,id=sata \
	-device ich9-intel-hda -device hda-output \
	-netdev user,id=net0 \
	-device e1000-82545em,netdev=net0,id=net0,mac=aa:bb:cc:dd:ee:ff \
	-vga std \
	-cdrom "$1" \

