#!/bin/sh

wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --yes --output /usr/share/keyrings/oracle-virtualbox-2016.gpg --dearmor
. /etc/os-release && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian ${VERSION_CODENAME} contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list > /dev/null

sudo apt update
sudo apt install virtualbox-7.2 vboxmanage-bash-completion
sudo usermod -aG vboxusers "$(whoami)"

# since linux 6.2, kvm grabs vt-x/vd-d in bios at boot which prevents virtualbox from start vms
# this kernel parameter instructs kvm to only use virtualization when it needs it
if ! grep -q 'kvm.enable_virt_at_load=0' /etc/default/grub; then
    sudo sed -ie 's/GRUB_CMDLINE_LINUX_DEFAULT="/GRUB_CMDLINE_LINUX_DEFAULT="kvm.enable_virt_at_load=0 /g' /etc/default/grub
    sudo update-grub
fi
