#!/bin/sh

# If there are no batteries, do nothing
[ ! "$(ls -A /sys/class/power_supply)" ] && exit

# From Lukesmith's dotfiles: https://github.com/lukesmithxyz/voidrice
# Loop through all attached batteries.
for battery in /sys/class/power_supply/BAT?
do
	# Get its remaining capacity and charge status.
	capacity=$(cat "$battery"/capacity) || break
	status=$(sed "s/[Dd]ischarging/🔋/;s/[Nn]ot charging/🛑/;s/[Cc]harging/🔌/;s/[Uu]nknown/♻️/;s/[Ff]ull/⚡/" "$battery"/status)

	# If it is discharging and 25% or less, we will add a ❗ as a warning.
	[ "$capacity" -le 25 ] && [ "$status" = "🔋" ] && status="❗"

	echo "$status ${capacity}%"
done | sed 's/ *$//'
