#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid -f pavucontrol ;;
	2) $SCRIPTS/volume.sh mutemic && kill -SIGRTMIN+6 $(pgrep i3blocks) ;;
	3) $SCRIPTS/volume.sh mute && kill -SIGRTMIN+6 $(pgrep i3blocks) ;;
	4) $SCRIPTS/volume.sh inc && kill -SIGRTMIN+6 $(pgrep i3blocks) ;;
	5) $SCRIPTS/volume.sh dec && kill -SIGRTMIN+6 $(pgrep i3blocks) ;;
esac

icon='🔊'
volinfos="$(pactl list sinks)"
echo "$volinfos" | grep -q 'Mute: yes' && icon='🔇'
volume="$(echo "$volinfos" | grep '[0-9]\+%' | sed "s,.* \([0-9]\+\)%.*,\1,;1q")"
echo "$icon $volume%"
