#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid -f pavucontrol ;;
	2) $SCRIPTS/volume.sh mutemic ;;
	3) $SCRIPTS/volume.sh mute ;;
	4) $SCRIPTS/volume.sh inc ;;
	5) $SCRIPTS/volume.sh dec ;;
esac

icon='🔊'
volinfos="$(pactl list sinks)"
echo "$volinfos" | grep -q 'Mute: yes' && icon='🔇'
volume="$(echo "$volinfos" | grep '[0-9]\+%' | sed "s,.* \([0-9]\+\)%.*,\1,;1q")"
echo "$icon $volume%"
